spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.10.10.51:5432/velto_test_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: PostgreSql
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    uz.uwon.pharm: INFO
    org.springframework.security: WARN
